export const FETCH_DRUGS_REQUEST         = 'FETCH_DRUGS_REQUEST';
export const FETCH_DRUGS_BY_NAME_SUCCESS = 'FETCH_DRUGS_BY_NAME_SUCCESS';
export const FETCH_DRUGS_BY_NAME_ERROR   = 'FETCH_DRUGS_BY_NAME_ERROR';

export const FETCH_DRUGS_SUCCESS         = 'FETCH_DRUGS_SUCCESS';
export const FETCH_DRUGS_ERROR           = 'FETCH_DRUGS_ERROR';
