export const FETCH_DRUGS_REQUEST = 'FETCH_DRUGS_REQUEST';
export const FETCH_DRUGS_BY_TITLE_SUCCESS = 'FETCH_DRUGS_BY_TITLE_SUCCESS';
export const FETCH_DRUGS_BY_TITLE_ERROR = 'FETCH_DRUGS_BY_TITLE_ERROR';

export const FETCH_DRUGS_SUCCESS = 'FETCH_BOOK_SUCCESS';
export const FETCH_DRUGS_ERROR = 'FETCH_DRUGS_ERROR';
