export const FETCH_DRUGS_REQUEST         = 'FETCH_DRUGS_REQUEST';
export const FETCH_DRUGS_BY_NAME_SUCCESS = 'FETCH_DRUGS_BY_NAME_SUCCESS';
export const FETCH_DRUGS_BY_NAME_ERROR   = 'FETCH_DRUGS_BY_NAME_ERROR';

export const FETCH_DRUGS_SUCCESS         = 'FETCH_DRUGS_SUCCESS';
export const FETCH_DRUGS_ERROR           = 'FETCH_DRUGS_ERROR';

export const UPDATE_INPUT_VALUE          = 'UPDATE_INPUT_VALUE';
export const CLEAR_SUGGESTIONS           = 'CLEAR_SUGGESTIONS';
export const MAYBE_UPDATE_SUGGESTIONS    = 'MAYBE_UPDATE_SUGGESTIONS';
export const LOAD_SUGGESTIONS_BEGIN      = 'LOAD_SUGGESTIONS_BEGIN';
