// Constants
export const
  FETCH_MEDICATION_HISTORY_SUCCESS = 'FETCH_MEDICATION_HISTORY_SUCCESS';
export const
  FETCH_MEDICATION_HISTORY_ERROR = 'FETCH_MEDICATION_HISTORY_ERROR';
export const
  UPDATE_MEDICATION_HISTORY_SUCCESS = 'UPDATE_MEDICATION_HISTORY_SUCCESS';
export const
  UPDATE_MEDICATION_HISTORY_ERROR = 'UPDATE_MEDICATION_HISTORY_ERROR';
