export const UPDATE_INPUT_VALUE          = 'UPDATE_INPUT_VALUE';
export const CLEAR_SUGGESTIONS           = 'CLEAR_SUGGESTIONS';
export const MAYBE_UPDATE_SUGGESTIONS    = 'MAYBE_UPDATE_SUGGESTIONS';
export const LOAD_SUGGESTIONS_BEGIN      = 'LOAD_SUGGESTIONS_BEGIN';
