// Constants
const FETCH_FORMULARY_REQUEST             = 'FETCH_FORMULARY_REQUEST';
const FETCH_FORMULARY_SUCCESS             = 'FETCH_FORMULARY_SUCCESS';
const FETCH_FORMULARY_ERROR               = 'FETCH_FORMULARY_ERROR';

const SWITCH_FORMULARY_PBM_SUCCESS        = 'SWITCH_FORMULARY_PBM_SUCCESS';
const SWITCH_FORMULARY_PBM_ERROR          = 'SWITCH_FORMULARY_PBM_ERROR';

const SELECT_FORMULARY_MEDICATION_SUCCESS = 'SELECT_FORMULARY_MEDICATION_SUCCESS';
const SELECT_FORMULARY_MEDICATION_ERROR   = 'SELECT_FORMULARY_MEDICATION_ERROR';


export {
  FETCH_FORMULARY_SUCCESS,
  FETCH_FORMULARY_ERROR,
  FETCH_FORMULARY_REQUEST,

  SELECT_FORMULARY_MEDICATION_SUCCESS,
  SELECT_FORMULARY_MEDICATION_ERROR,

  SWITCH_FORMULARY_PBM_SUCCESS,
  SWITCH_FORMULARY_PBM_ERROR
};
